In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [60]:
from sklearn.datasets import load_wine

In [61]:
data=load_wine()
data

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [62]:
data1=pd.DataFrame(data['data'],columns=data['feature_names'])

In [63]:
data1

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [64]:
data1['class']=data['target']

In [65]:
data1

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  class
0      14.23        1.71  2.43  ...                          3.92   1065.0      0
1      13.20        1.78  2.14  ...                          3.40   1050.0      0
2      13.16        2.36  2.67  ...                          3.17   1185.0      0
3      14.37        1.95  2.50  ...                          3.45   1480.0      0
4      13.24        2.59  2.87  ...                          2.93    735.0      0
..       ...         ...   ...  ...                           ...      ...    ...
173    13.71        5.65  2.45  ...                          1.74    740.0      2
174    13.40        3.91  2.48  ...                          1.56    750.0      2
175    13.27        4.28  2.26  ...                          1.56    835.0      2
176    13.17        2.59  2.37  ...                          1.62    840.0      2
177    14.13        4.10  2.74  ...                          1.60    560.0      2

[178 rows x 14 columns]

In [66]:
data1['class']=data1['class'].replace(to_replace=[0,1,2],value=['class_0','class_1','class_2'])

In [67]:
data1

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline    class
0      14.23        1.71  2.43  ...                          3.92   1065.0  class_0
1      13.20        1.78  2.14  ...                          3.40   1050.0  class_0
2      13.16        2.36  2.67  ...                          3.17   1185.0  class_0
3      14.37        1.95  2.50  ...                          3.45   1480.0  class_0
4      13.24        2.59  2.87  ...                          2.93    735.0  class_0
..       ...         ...   ...  ...                           ...      ...      ...
173    13.71        5.65  2.45  ...                          1.74    740.0  class_2
174    13.40        3.91  2.48  ...                          1.56    750.0  class_2
175    13.27        4.28  2.26  ...                          1.56    835.0  class_2
176    13.17        2.59  2.37  ...                          1.62    840.0  class_2
177    14.13        4.10  2.74  ...                          1.60    560.0  class_2

[178 rows x 14 columns]

In [76]:
from sklearn.model_selection import train_test_split
x=data1.iloc[:,0:-1]
y=data1.iloc[:,13:14]
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=1)

In [77]:
xtrain

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
91     12.00        1.51  2.42  ...  1.05                          2.65    450.0
81     12.72        1.81  2.20  ...  1.16                          3.14    714.0
114    12.08        1.39  2.50  ...  0.93                          3.19    385.0
48     14.10        2.02  2.40  ...  1.07                          2.75   1060.0
54     13.74        1.67  2.25  ...  0.92                          3.20   1060.0
..       ...         ...   ...  ...   ...                           ...      ...
133    12.70        3.55  2.36  ...  0.78                          1.29    600.0
137    12.53        5.51  2.64  ...  0.82                          1.69    515.0
72     13.49        1.66  2.24  ...  0.98                          2.78    472.0
140    12.93        2.81  2.70  ...  0.77                          2.31    600.0
37     13.05        1.65  2.55  ...  1.12                          2.51   1105.0

[142 rows x 13 columns]

In [78]:
ytrain

class
91   class_1
81   class_1
114  class_1
48   class_0
54   class_0
..       ...
133  class_2
137  class_2
72   class_1
140  class_2
37   class_0

[142 rows x 1 columns]

In [79]:
xtest

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
161    13.69        3.26  2.54  ...  0.96                          1.82    680.0
117    12.42        1.61  2.19  ...  1.06                          2.96    345.0
19     13.64        3.10  2.56  ...  0.96                          3.36    845.0
69     12.21        1.19  1.75  ...  1.28                          3.07    718.0
53     13.77        1.90  2.68  ...  1.13                          2.93   1375.0
138    13.49        3.59  2.19  ...  0.81                          1.82    580.0
112    11.76        2.68  2.92  ...  1.23                          2.50    607.0
14     14.38        1.87  2.38  ...  1.20                          3.00   1547.0
160    12.36        3.83  2.38  ...  0.56                          1.58    520.0
107    12.72        1.75  2.28  ...  0.88                          2.42    488.0
11     14.12        1.48  2.32  ...  1.17                          2.82   1280.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
108    12.22        1.29  1.94  ...  0.86                          3.02    312.0
42     13.88        1.89  2.59  ...  0.88                          3.56   1095.0
84     11.84        0.89  2.58  ...  0.79                          3.08    520.0
113    11.41        0.74  2.50  ...  1.10                          2.31    434.0
152    13.11        1.90  2.75  ...  0.61                          1.33    425.0
35     13.48        1.81  2.41  ...  1.04                          3.47    920.0
105    12.42        2.55  2.27  ...  0.86                          3.30    315.0
31     13.58        1.66  2.36  ...  1.09                          2.88   1515.0
51     13.83        1.65  2.60  ...  1.24                          3.37   1265.0
126    12.43        1.53  2.29  ...  0.69                          2.84    352.0
130    12.86        1.35  2.32  ...  0.76                          1.29    630.0
73     12.99        1.67  2.60  ...  1.31                          3.50    985.0
40     13.56        1.71  2.31  ...  0.95                          3.38    795.0
162    12.85        3.27  2.58  ...  0.87                          2.11    570.0
47     13.90        1.68  2.12  ...  0.91                          3.33    985.0
29     14.02        1.68  2.21  ...  1.04                          3.59   1035.0
16     14.30        1.92  2.72  ...  1.07                          2.65   1280.0
147    12.87        4.61  2.48  ...  0.54                          1.86    625.0
97     12.29        1.41  1.98  ...  1.23                          2.74    428.0
159    13.48        1.67  2.64  ...  0.57                          1.78    620.0
151    12.79        2.67  2.48  ...  0.48                          1.47    480.0
5      14.20        1.76  2.45  ...  1.05                          2.85   1450.0
120    11.45        2.40  2.42  ...  0.80                          3.39    625.0
94     11.62        1.99  2.28  ...  1.16                          2.96    345.0

[36 rows x 13 columns]

In [80]:
xtrain.shape

(142, 13)

In [81]:
ytrain.shape

(142, 1)

In [82]:
xtest.shape

(36, 13)

In [83]:
ytest.shape

(36, 1)

In [84]:
from sklearn.preprocessing import MinMaxScaler

In [85]:
scaler=MinMaxScaler()
xtrain_transform=scaler.fit_transform(xtrain)
xtest_transform=scaler.fit_transform(xtest)
xtrain_transform[:10]

array([[0.25526316, 0.1244898 , 0.56684492, 0.63687151, 0.17391304,
        0.16206897, 0.19198312, 0.74      , 0.38485804, 0.19795222,
        0.43103448, 0.50549451, 0.12268188],
       [0.44473684, 0.18571429, 0.44919786, 0.45810056, 0.17391304,
        0.42068966, 0.46202532, 0.26      , 0.42902208, 0.22354949,
        0.52586207, 0.68498168, 0.31098431],
       [0.27631579, 0.1       , 0.60962567, 0.66480447, 0.15217391,
        0.54482759, 0.41139241, 0.6       , 0.19873817, 0.13822526,
        0.32758621, 0.7032967 , 0.07631954],
       [0.80789474, 0.22857143, 0.55614973, 0.45810056, 0.35869565,
        0.61034483, 0.5443038 , 0.38      , 0.6214511 , 0.41979522,
        0.44827586, 0.54212454, 0.55777461],
       [0.71315789, 0.15714286, 0.47593583, 0.32402235, 0.52173913,
        0.55862069, 0.54008439, 0.16      , 0.38170347, 0.38993174,
        0.31896552, 0.70695971, 0.55777461],
       [0.35263158, 0.00816327, 0.        , 0.        , 0.19565217,
        0.34482759, 0.04852

In [86]:
xtest_transform

array([[0.76767677, 0.65116279, 0.67521368, 0.44444444, 0.34328358,
        0.234375  , 0.02531646, 0.69230769, 0.        , 0.39422085,
        0.57831325, 0.23043478, 0.29797571],
       [0.34006734, 0.2248062 , 0.37606838, 0.58333333, 0.35820896,
        0.32291667, 0.50949367, 0.38461538, 0.375     , 0.        ,
        0.69879518, 0.72608696, 0.02672065],
       [0.75084175, 0.60981912, 0.69230769, 0.17777778, 0.47761194,
        0.6875    , 0.80696203, 0.05769231, 0.39814815, 0.31372549,
        0.57831325, 0.9       , 0.43157895],
       [0.26936027, 0.11627907, 0.        , 0.26666667, 1.        ,
        0.24479167, 0.25316456, 0.        , 0.78703704, 0.08152735,
        0.96385542, 0.77391304, 0.32874494],
       [0.79461279, 0.2997416 , 0.79487179, 0.28333333, 0.46268657,
        0.84375   , 0.73101266, 0.48076923, 0.40740741, 0.4375645 ,
        0.78313253, 0.71304348, 0.86072874],
       [0.7003367 , 0.73643411, 0.37606838, 0.41666667, 0.05970149,
        0.125     , 0.     

In [87]:
from sklearn.neural_network import MLPClassifier

In [88]:
model=MLPClassifier(hidden_layer_sizes=(150,100,45),activation='relu',max_iter=300,solver='adam')

In [89]:
model.fit(xtrain_transform,ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(hidden_layer_sizes=(150, 100, 45), max_iter=300)

In [90]:
ypred=model.predict(xtest_transform)

In [91]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [92]:
accuracy=accuracy_score(ytest,ypred)
accuracy

0.9722222222222222

In [93]:
cm=confusion_matrix(ytest,ypred)
cm

array([[14,  0,  0],
       [ 0, 13,  0],
       [ 0,  1,  8]])